version: '3.8'

services:
  backend:
    build:
      context: ./Nest Back-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./Nest Back-end:/app
      - /app/node_modules

  frontend:
    build:
      context: ./React_Front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - .env
    volumes:
      - ./React_Front:/app
      - /app/node_modules
