version: '3.8'

services:
  backend:
    build:
      context: ./Nest Back-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./Nest Back-end:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

  frontend:
    build:
      context: ./React_Front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - .env
    volumes:
      - ./React_Front:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
