name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    # Install dependencies and run tests for backend
    - name: Install Backend Dependencies
      working-directory: ./Nest Back-end
      run: npm install

    - name: Run Backend Tests
      working-directory: ./Nest Back-end
      run: npm test

    # Install dependencies and run tests for frontend
    - name: Install Frontend Dependencies
      working-directory: ./React_Front
      run: npm install
    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Build and push Docker images
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build and push backend
    - name: Build and push Backend
      uses: docker/build-push-action@v4
      with:
        context: ./Nest Back-end
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

    # Build and push frontend
    - name: Build and push Frontend
      uses: docker/build-push-action@v4
      with:
        context: ./React_Front
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest 